`Pandas is used on excel data for data cleaning and data transformation `

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
len(dir(pd))

141

**Some Important Pandas Built_in_Functions for AI**

- `Series`
- `DataFrame`
- `shape `
- `size`
- `loc and iloc `
- `rename `
- `drop `
- `axis=1`
- `axis=0`
- `to_csv`
- `read_csv`
- `head`
- `tail `
- `sample `
- `isnull().sum()`
- `info()`
- `unique `
- `value_counts`
- `select_dtypes`
- `groupBy`
- `fillna `
- `dropna `
- `index `
- `columns `

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# Series = we can create only 1 column

a = np.array([10,20,50,90,40]) # 1D

b = pd.Series(a,index = ['r1','r2','r3','r4','r5'])

b

r1    10
r2    20
r3    50
r4    90
r5    40
dtype: int64

In [ ]:
b['r3']

np.int64(50)

In [ ]:
b[2]

np.int64(50)

In [ ]:
# DataFrame = we can use to create proper excel data

a = {'Name' : ['John','Peter','Steve','Brad','Smith','Hasan'],
     'Location':['USA','UK','CANADA','India','Paris','Dubai'],
     'Age':[20,21,25,29,32,34],
     'Company' : ['Google','Meta','IBM','MSFT','Wipro','Delloite'],
     'Salary':[1200,1400,1500,1900,2400,4500]
     }


b = pd.DataFrame(a,index = ['r1','r2','r3','r4','r5','r6'])

b

     Name Location  Age   Company  Salary
r1   John      USA   20    Google    1200
r2  Peter       UK   21      Meta    1400
r3  Steve   CANADA   25       IBM    1500
r4   Brad    India   29      MSFT    1900
r5  Smith    Paris   32     Wipro    2400
r6  Hasan    Dubai   34  Delloite    4500

In [ ]:
b['Location']['r5'] = 'China'

In [ ]:
b['Company']['r3']

'IBM'

In [ ]:
b['Age']['r5']

np.int64(32)

In [ ]:
b.shape

(6, 5)

In [ ]:
b.size

30

In [ ]:
b

     Name Location  Age   Company  Salary
r1   John      USA   20    Google    1200
r2  Peter       UK   21      Meta    1400
r3  Steve   CANADA   25       IBM    1500
r4   Brad    India   29      MSFT    1900
r5  Smith    China   32     Wipro    2400
r6  Hasan    Dubai   34  Delloite    4500

In [ ]:
# loc will not use (n-1) and no index
# iloc will use (n-1) and index

In [ ]:
b.loc['r2':'r4' , 'Location':'Company']

   Location  Age Company
r2       UK   21    Meta
r3   CANADA   25     IBM
r4    India   29    MSFT

In [ ]:
b.loc['r3':'r4' , 'Name':'Company']

     Name Location  Age Company
r3  Steve   CANADA   25     IBM
r4   Brad    India   29    MSFT

In [ ]:
b.iloc[1:4 , 1:4]

   Location  Age Company
r2       UK   21    Meta
r3   CANADA   25     IBM
r4    India   29    MSFT

In [ ]:
b.iloc[2:4 , 0:4]

     Name Location  Age Company
r3  Steve   CANADA   25     IBM
r4   Brad    India   29    MSFT

In [ ]:
b.loc['r2':'r5' , 'Location':'Company']

   Location  Age Company
r2       UK   21    Meta
r3   CANADA   25     IBM
r4    India   29    MSFT
r5    China   32   Wipro

In [ ]:
b.iloc[1:5 , 1:4]

   Location  Age Company
r2       UK   21    Meta
r3   CANADA   25     IBM
r4    India   29    MSFT
r5    China   32   Wipro

In [ ]:
b

     Name Location  Age   Company  Salary
r1   John      USA   20    Google    1200
r2  Peter       UK   21      Meta    1400
r3  Steve   CANADA   25       IBM    1500
r4   Brad    India   29      MSFT    1900
r5  Smith    China   32     Wipro    2400
r6  Hasan    Dubai   34  Delloite    4500

In [ ]:
c = b.iloc[ : , 1:3]
c

   Location  Age
r1      USA   20
r2       UK   21
r3   CANADA   25
r4    India   29
r5    China   32
r6    Dubai   34

In [ ]:
b

     Name Location  Age   Company  Salary
r1   John      USA   20    Google    1200
r2  Peter       UK   21      Meta    1400
r3  Steve   CANADA   25       IBM    1500
r4   Brad    India   29      MSFT    1900
r5  Smith    China   32     Wipro    2400
r6  Hasan    Dubai   34  Delloite    4500

In [ ]:
b.columns

Index(['Name', 'Location', 'Age', 'Company', 'Salary'], dtype='object')

In [ ]:
b.index

Index(['r1', 'r2', 'r3', 'r4', 'r5', 'r6'], dtype='object')

In [ ]:
b

     Name Location  Age   Company  Salary
r1   John      USA   20    Google    1200
r2  Peter       UK   21      Meta    1400
r3  Steve   CANADA   25       IBM    1500
r4   Brad    India   29      MSFT    1900
r5  Smith    China   32     Wipro    2400
r6  Hasan    Dubai   34  Delloite    4500

In [ ]:
b['Age'] = [1,2,3,4,5,6]

In [ ]:
b

     Name Location  Age   Company  Salary
r1   John      USA    1    Google    1200
r2  Peter       UK    2      Meta    1400
r3  Steve   CANADA    3       IBM    1500
r4   Brad    India    4      MSFT    1900
r5  Smith    China    5     Wipro    2400
r6  Hasan    Dubai    6  Delloite    4500

In [ ]:
b['Tax'] = [10,20,50,60,70,5]

In [ ]:
b

     Name Location  Age   Company  Salary  Tax
r1   John      USA    1    Google    1200   10
r2  Peter       UK    2      Meta    1400   20
r3  Steve   CANADA    3       IBM    1500   50
r4   Brad    India    4      MSFT    1900   60
r5  Smith    China    5     Wipro    2400   70
r6  Hasan    Dubai    6  Delloite    4500    5

In [ ]:
b['TDS'] = [150,160,np.nan,200,np.nan,250]

In [ ]:
b

     Name Location  Age   Company  Salary  Tax    TDS
r1   John      USA    1    Google    1200   10  150.0
r2  Peter       UK    2      Meta    1400   20  160.0
r3  Steve   CANADA    3       IBM    1500   50    NaN
r4   Brad    India    4      MSFT    1900   60  200.0
r5  Smith    China    5     Wipro    2400   70    NaN
r6  Hasan    Dubai    6  Delloite    4500    5  250.0

In [ ]:
b['TDS'] = b['TDS'].fillna(120)

In [ ]:
# b = b.dropna()

In [ ]:
b

     Name Location  Age   Company  Salary  Tax    TDS
r1   John      USA    1    Google    1200   10  150.0
r2  Peter       UK    2      Meta    1400   20  160.0
r3  Steve   CANADA    3       IBM    1500   50  120.0
r4   Brad    India    4      MSFT    1900   60  200.0
r5  Smith    China    5     Wipro    2400   70  120.0
r6  Hasan    Dubai    6  Delloite    4500    5  250.0

In [ ]:
# axis = 1 (column)
# axis = 0 (row)
# drop

b = b.drop(['Age'],axis=1)

In [ ]:
b

     Name Location   Company  Salary  Tax    TDS
r1   John      USA    Google    1200   10  150.0
r2  Peter       UK      Meta    1400   20  160.0
r3  Steve   CANADA       IBM    1500   50  120.0
r4   Brad    India      MSFT    1900   60  200.0
r5  Smith    China     Wipro    2400   70  120.0
r6  Hasan    Dubai  Delloite    4500    5  250.0

In [ ]:
b = b.rename(columns={'Tax':'Income_Tax'})

In [ ]:
b

     Name Location   Company  Salary  Income_Tax    TDS
r1   John      USA    Google    1200          10  150.0
r2  Peter       UK      Meta    1400          20  160.0
r3  Steve   CANADA       IBM    1500          50  120.0
r4   Brad    India      MSFT    1900          60  200.0
r5  Smith    China     Wipro    2400          70  120.0
r6  Hasan    Dubai  Delloite    4500           5  250.0

In [ ]:
b.to_csv('Own_data.csv',index=False)

In [ ]:
# load data from excel sheet

In [ ]:
df = pd.read_csv('/content/Titanic-Dataset.csv')

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.shape

(891, 12)

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [ ]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
577 + 314

891

In [ ]:
df.head() # frist 5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.tail() # last 5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
df.sample(5) # random

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
354,355,0,3,"Yousif, Mr. Wazli",male,NaN,0,0,2647,7.2250,NaN,C
577,578,1,1,"Silvey, Mrs. William Baird (Alice Munger)",female,39.0,1,0,13507,55.9000,E44,S
667,668,0,3,"Rommetvedt, Mr. Knud Paust",male,NaN,0,0,312993,7.7750,NaN,S
656,657,0,3,"Radeff, Mr. Alexander",male,NaN,0,0,349223,7.8958,NaN,S
501,502,0,3,"Canavan, Miss. Mary",female,21.0,0,0,364846,7.7500,NaN,Q

In [ ]:
num_cols = df.select_dtypes(exclude='object')

In [ ]:
num_cols

     PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0              1         0       3  22.0      1      0   7.2500
1              2         1       1  38.0      1      0  71.2833
2              3         1       3  26.0      0      0   7.9250
3              4         1       1  35.0      1      0  53.1000
4              5         0       3  35.0      0      0   8.0500
..           ...       ...     ...   ...    ...    ...      ...
886          887         0       2  27.0      0      0  13.0000
887          888         1       1  19.0      0      0  30.0000
888          889         0       3   NaN      1      2  23.4500
889          890         1       1  26.0      0      0  30.0000
890          891         0       3  32.0      0      0   7.7500

[891 rows x 7 columns]

In [ ]:
text_columns = df.select_dtypes(include='object')

In [ ]:
text_columns

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [ ]:
df = df.drop(['PassengerId','Name','Ticket'],axis=1)

In [ ]:
df = df.dropna()

In [ ]:
df.shape

(183, 9)

In [ ]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
1,1,1,female,38.0,1,0,71.2833,C85,C
3,1,1,female,35.0,1,0,53.1000,C123,S
6,0,1,male,54.0,0,0,51.8625,E46,S
10,1,3,female,4.0,1,1,16.7000,G6,S
11,1,1,female,58.0,0,0,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,D35,S
872,0,1,male,33.0,0,0,5.0000,B51 B53 B55,S
879,1,1,female,56.0,0,1,83.1583,C50,C
887,1,1,female,19.0,0,0,30.0000,B42,S
889,1,1,male,26.0,0,0,30.0000,C148,C

In [ ]:
df.to_csv('Titanic_cleaned_data.csv',index=False)

In [ ]:
a = pd.DataFrame({'Animal':['Lion','Tiger','Lion','Tiger','Lion','Tiger'],
                  'Speed':[80,180,100,200,120,220]
                  })


a

  Animal  Speed
0   Lion     80
1  Tiger    180
2   Lion    100
3  Tiger    200
4   Lion    120
5  Tiger    220

In [ ]:
a.groupby(['Animal']).sum()

        Speed
Animal
Lion      300
Tiger     600

In [ ]:
a.groupby(['Animal']).mean()

        Speed
Animal
Lion    100.0
Tiger   200.0